### ISSUE TITLE
bug com vglNdarray3To4Channels();

### ISSUE THREAD

**Issue by davyobs** [ddantas/visiongl#5]
A função "vglNdarray3To4Channels(img);" dá segmentation fault com imagens com 1 canal.

**Comment by HDANILO** [comment]
Não é bug, como diz a propria função, ela converte de 3 para 4, não de 1 para 4, poderia até apresentar mensagem de erro mas acho até desnecessário!

**Comment by davyobs** [comment]
Realmente não é bug mesmo não, é que não lembrei de um termo mais apropriado. Daniel que pediu para eu deixar a mensagem aqui para poder colocar para apresentar uma mensagem de erro ao invés de dar segmentation fault.
